Repository packit/packit, pull requests merged in 2019-09, with the labels that each got.

#507 Fully configurable SRPM process
  packit/actions.py
  packit/api.py
  packit/base_git.py
  packit/command_handler.py
  packit/config.py
  packit/local_project.py
  packit/schema.py
  packit/upstream.py
  packit/utils.py
  setup.cfg
  tests/data/cockpit-ostree/cockpit-ostree.spec.dg
  tests/data/osbuild/.packit.yaml
  tests/data/osbuild/__init__.py
  tests/data/osbuild/osbuild.spec
  tests/data/osbuild/setup.py
  tests/data/snapd/.packit.yaml
  tests/data/snapd/packaging/fedora/fix-spec
  tests/data/snapd/packaging/fedora/pack-source
  tests/data/snapd/packaging/fedora/snapd.spec
  tests/data/snapd/vendor/vendor.json
  tests/integration/test_actions.py
  tests/integration/test_base_git.py
  tests/integration/test_using_cockpit.py
  tests/integration/test_using_osbuild.py
  tests/integration/test_using_snapd.py
  tests/spellbook.py
  tests/unit/test_base_git.py
Labels: ready-for-review

#522 Skip test if sandcastle can't be imported
  tests/testsuite_basic/integration/test_base_git.py
Labels: mergeit

#483 Unify getting ogr projects
  packit/api.py
  packit/config.py
  packit/distgit.py
  packit/local_project.py
  packit/schema.py
  packit/status.py
  packit/upstream.py
  setup.cfg
  tests/testsuite_basic/data/cockpit-ostree/packit.yaml
  tests/testsuite_basic/data/osbuild/.packit.yaml
  tests/testsuite_basic/data/snapd/.packit.yaml
  tests/testsuite_basic/integration/test_upstream.py
  tests/testsuite_basic/unit/test_config.py
  tests/testsuite_recording/integration/test_api.py
  tests/testsuite_recording/integration/test_data/test_api/tests.testsuite_recording.integration.test_api.ProposeUpdate.test_propose_update.yaml
  tests/testsuite_recording/integration/test_data/test_status/tests.testsuite_recording.integration.test_status.TestStatus.test_distgen_versions.yaml
  tests/testsuite_recording/integration/test_data/test_status/tests.testsuite_recording.integration.test_status.TestStatus.test_dowstream_pr.yaml
  tests/testsuite_recording/integration/testbase.py
Labels: mergeit, ready-for-review

#535 fix-spec: raise when upstream_project_name is not set
  packit.spec
  packit/upstream.py
  tests/testsuite_basic/integration/test_upstream.py
Labels: mergeit
