Repository packit/packit, pull requests merged in 2019-07, with the labels that each got.

#394 utilize new sandcastle api and revert the workaround
  .packit.yaml
  packit/command_handler.py
  packit/upstream.py
  tests/integration/test_data/test_status/tests.integration.test_status.TestStatus.test_builds_github.yaml
  tests/integration/test_data/test_status/tests.integration.test_status.TestStatus.test_distgen_versions_github.yaml
  tests/integration/test_data/test_status/tests.integration.test_status.TestStatus.test_dowstream_pr_github.yaml
  tests/integration/test_data/test_status/tests.integration.test_status.TestStatus.test_status_github.yaml
  tests/integration/test_data/test_status/tests.integration.test_status.TestStatus.test_up_releases_github.yaml
  tests/integration/test_data/test_status/tests.integration.test_status.TestStatus.test_updates_github.yaml
  tests/integration/testbase.py
Labels: ready-for-review

#404 preserve %changelog and bump spec when updating in fedora
  packit/api.py
  packit/base_git.py
  packit/command_handler.py
  packit/upstream.py
  packit/utils.py
  tests/data/dist_git/beer.spec
  tests/integration/test_source_git.py
  tests/integration/test_update.py
Labels: ready-for-review

#402 Dirrect push to distgit
  packit/api.py
  packit/cli/sync_from_downstream.py
  packit/cli/update.py
  tests/conftest.py
  tests/integration/test_update.py
Labels: feature, ready-for-review

#401 support copr builds in CLI
  packit/api.py
  packit/cli/copr_build.py
  packit/cli/packit_base.py
  packit/constants.py
Labels: ready-for-review

#425 Update ogr related code
  CONTRIBUTING.md
  files/install-requirements.yaml
  files/tasks/generic-dnf-requirements.yaml
  packit/config.py
  packit/ogr_services.py
  packit/upstream.py
  tests/__init__.py
  tests/integration/__init__.py
  tests/integration/test_data/test_status/tests.integration.test_status.TestStatus.test_builds.yaml
  tests/integration/test_data/test_status/tests.integration.test_status.TestStatus.test_builds_pagure.yaml
  tests/integration/test_data/test_status/tests.integration.test_status.TestStatus.test_distgen_versions.yaml
  tests/integration/test_data/test_status/tests.integration.test_status.TestStatus.test_distgen_versions_pagure.yaml
  tests/integration/test_data/test_status/tests.integration.test_status.TestStatus.test_dowstream_pr.yaml
  tests/integration/test_data/test_status/tests.integration.test_status.TestStatus.test_dowstream_pr_pagure.yaml
  tests/integration/test_data/test_status/tests.integration.test_status.TestStatus.test_status.yaml
  tests/integration/test_data/test_status/tests.integration.test_status.TestStatus.test_status_pagure.yaml
  tests/integration/test_data/test_status/tests.integration.test_status.TestStatus.test_up_releases.yaml
  tests/integration/test_data/test_status/tests.integration.test_status.TestStatus.test_up_releases_github.yaml
  tests/integration/test_data/test_status/tests.integration.test_status.TestStatus.test_up_releases_pagure.yaml
  tests/integration/test_data/test_status/tests.integration.test_status.TestStatus.test_updates.yaml
  tests/integration/test_data/test_status/tests.integration.test_status.TestStatus.test_updates_pagure.yaml
  tests/integration/test_upstream.py
  tests/integration/testbase.py
Labels: OGR, testing
