Repository packit/packit, pull requests merged in 2019-04, with the labels that each got.

#231 sourcegit support (#213 follow up)
  docs/actions.md
  docs/configuration.md
  packit/actions.py
  packit/api.py
  packit/base_git.py
  packit/config.py
  packit/distgit.py
  packit/upstream.py
  tests/integration/test_base_git.py
  tests/unit/test_actions.py
  tests/unit/test_base_git.py
  tests/unit/test_config.py
Labels: docs, enhancement, refactor, source-git

#249 Support multiple sources in sync files
  docs/configuration.md
  packit/config.py
  packit/sync.py
  tests/data/sync_files/a.md
  tests/data/sync_files/b.md
  tests/data/sync_files/c.txt
  tests/integration/test_sync_files.py
  tests/unit/test_config.py
  tests/unit/test_sync.py
Labels: enhancement

#252 Implement jobs
  docs/configuration.md
  packit/api.py
  packit/bot_api.py
  packit/config.py
  packit/exceptions.py
  packit/jobs.py
  packit/schema.py
  packit/service/web_hook.py
  packit/status.py
  packit/utils.py
  tests/data/upstream_git/.packit.json
  tests/unit/test_config.py
  tests/unit/test_steve.py
Labels: ready-for-review

#261 Update from downstream branch 'master'
  .packit.yaml
  fedora-tests/simple.py
  fedora-tests/tests.yml
  fedora-tests/upstream.sh
Labels: ready-for-review

#259 Source git for SRPM
  docs/srpm.md
  packit/api.py
  packit/base_git.py
  packit/cli/sourcegit_to_dist_git.py
  packit/cli/sourcegit_to_srpm.py
  packit/cli/srpm.py
  packit/config.py
  packit/distgit.py
  packit/local_project.py
  packit/upstream.py
  packit/utils.py
  tests/conftest.py
  tests/data/upstream_git/beer.spec
  tests/functional/test_srpm.py
  tests/integration/test_source_git.py
  tests/integration/test_update.py
  tests/unit/test_config.py
  tests/unit/test_local_project.py
  tests/utils.py
Labels: ready-for-review

#263 unify fedmsg parsing into a single command
  docs/configuration.md
  packit/api.py
  packit/base_git.py
  packit/bot_api.py
  packit/cli/listen_to_fedmsg.py
  packit/cli/packit_base.py
  packit/cli/watch_fedora_ci.py
  packit/cli/watch_upstream_release.py
  packit/config.py
  packit/constants.py
  packit/fed_mes_consume.py
  packit/jobs.py
  packit/local_project.py
  packit/schema.py
  packit/service/web_hook.py
  packit/status.py
  packit/sync.py
  packit/upstream.py
  tests/conftest.py
  tests/data/upstream_git/.packit.json
  tests/integration/test_listen_to_fedmsg.py
  tests/integration/test_status.py
  tests/integration/test_sync_files.py
  tests/integration/test_update.py
  tests/unit/test_cli.py
  tests/unit/test_steve.py
  tests/unit/test_sync.py
Labels: ready-for-review

#279 image build: cache packages installation
  Dockerfile
  Makefile
  files/install-rpm-packages.yaml
  recipe.yaml
Labels: ready-for-review
