Repository packit/packit, pull requests merged in 2020-10, with the labels that each got.

#922 Forward info whether to use stg (fedpkg-stage, kinit) via PackitAPI
  packit/api.py
  packit/config/common_package_config.py
  packit/config/config.py
  packit/constants.py
  packit/distgit.py
  packit/schema.py
  tests/unit/test_config.py
Labels: mergeit

#952 Use archive in Upstream._fix_spec_prep
  packit/config/common_package_config.py
  packit/config/job_config.py
  packit/config/package_config.py
  packit/schema.py
  packit/upstream.py
  tests/integration/conftest.py
  tests/integration/test_upstream.py
  tests/unit/test_upstream.py
Labels: mergeit, ready-for-review

#985 [sync_release] reset the branch correctly
  packit/api.py
Labels: mergeit

#988 [Zuul] Remove files/tasks/zuul-project-setup.yaml
  files/tasks/zuul-project-setup.yaml
  files/zuul-install-requirements-rpms.yaml
  files/zuul-reverse-dep-packit-service.yaml
  files/zuul-tests-session-recording.yaml
  files/zuul-tests.yaml
Labels: mergeit

#990 [files/zuul-tests*.yaml] set default project_dir
  files/zuul-tests-session-recording.yaml
  files/zuul-tests.yaml
Labels: mergeit

#987 Allow symlinking absolute path to archive
  packit/upstream.py
  tests/functional/test_srpm.py
Labels: mergeit

#995 no patches b/w refs: change logger.warning() to info
  packit/patches.py
Labels: hacktoberfest-accepted, mergeit

#997 Update pre-commit configuration for prettier
  .pre-commit-config.yaml
Labels: mergeit

#994 [sync_release] check for the existing pull requests in distgit
  packit/api.py
  packit/distgit.py
  tests/unit/test_dg.py
  tests_recording/test_data/test_api/tests_recording.test_api.ProposeUpdate.test_comment_in_spec.yaml
  tests_recording/test_data/test_api/tests_recording.test_api.ProposeUpdate.test_comment_in_spec.yaml.packit-dist-git_2_1.tar.xz
  tests_recording/test_data/test_api/tests_recording.test_api.ProposeUpdate.test_comment_in_spec.yaml.static_tmp_1_1.tar.xz
  tests_recording/test_data/test_api/tests_recording.test_api.ProposeUpdate.test_version_change_exception.yaml
  tests_recording/test_data/test_api/tests_recording.test_api.ProposeUpdate.test_version_change_exception.yaml.packit-dist-git_2_1.tar.xz
  tests_recording/test_data/test_api/tests_recording.test_api.ProposeUpdate.test_version_change_exception.yaml.static_tmp_1_1.tar.xz
  tests_recording/test_data/test_api/tests_recording.test_api.ProposeUpdate.test_version_change_mocked.yaml
  tests_recording/test_data/test_api/tests_recording.test_api.ProposeUpdate.test_version_change_mocked.yaml.packit-dist-git_2_1.tar.xz
  tests_recording/test_data/test_api/tests_recording.test_api.ProposeUpdate.test_version_change_mocked.yaml.static_tmp_1_1.tar.xz
Labels: mergeit

#1001 Add sync_changelog config option to missing places
  packit/config/package_config.py
  packit/schema.py
  tests/unit/test_package_config.py
Labels: mergeit
