Repository packit/packit, pull requests merged in 2020-09, with the labels that each got.

#955 Update pre-commit configuration
  .pre-commit-config.yaml
  packit/api.py
  packit/cli/copr_build.py
  packit/config/config.py
  packit/config/job_config.py
  packit/config/package_config.py
  packit/config/package_config_validator.py
  packit/copr_helper.py
  packit/distgit.py
  packit/local_project.py
  packit/patches.py
  packit/schema.py
  packit/status.py
  packit/upstream.py
  tests/integration/test_copr_build.py
  tests/integration/test_get_api.py
  tests/integration/test_source_git.py
  tests/integration/test_update.py
  tests/spellbook.py
  tests/unit/test_api.py
  tests/unit/test_config.py
  tests/unit/test_config_aliases.py
  tests/unit/test_git_utils.py
  tests/unit/test_load_authentication.py
  tests/unit/test_package_config.py
  tests/unit/test_security.py
Labels: mergeit

#958 Fix failing test in F33 and Rawhide
  tests/integration/test_upstream.py
Labels: mergeit

#967 pre-commit and black badge
  README.md
Labels: mergeit, 🌞 Friday 🤟

#966 Add pyupgrade to pre-commit
  .pre-commit-config.yaml
  packit/config/aliases.py
  tests/integration/test_source_git.py
Labels: 🌞 Friday 🤟

#959 Use upstream_tag_template to get version from tag
  packit/upstream.py
  tests/integration/test_upstream.py
  tests/unit/test_upstream.py
Labels: mergeit, ready-for-review

#968 Set REDIS_SERVICE_HOST in reverse-dep-p-s tests
  files/zuul-reverse-dep-packit-service.yaml
Labels: mergeit

#971 Fix copr project name for CLI
  packit/cli/copr_build.py
  tests/integration/test_copr_build.py
  tests/spellbook.py
Labels: mergeit

#972 PatchMetadata.from_commit: make path optional
  packit/patches.py
Labels: mergeit

#974 Don't drop zeros in version numbers
  packit/upstream.py
Labels: mergeit

#976 Update contribution guidelines
  CONTRIBUTING.md
Labels: mergeit

#977 cli: make --remote global
  packit/cli/local_build.py
  packit/cli/packit_base.py
  packit/cli/srpm.py
  packit/cli/sync_from_downstream.py
  packit/cli/types.py
  packit/cli/update.py
  packit/config/config.py
  packit/schema.py
  tests/functional/test_local_build.py
Labels: mergeit, 🌞 Friday 🤟

#978 patches: support git format-patch --no-prefix
  packit/patches.py
  tests/integration/test_source_git.py
  tests/spellbook.py
Labels: mergeit

#961 Use correct arguments in sync_release() from tests
  packit/api.py
  tests/integration/test_source_git.py
  tests/integration/test_update.py
  tests/integration/test_using_cockpit.py
  tests_recording/test_api.py
Labels: mergeit

#934 Don't leave distgit repository dirty after exc
  packit/api.py
  tests/data/cockpit-ostree/packit.yaml
  tests/data/sourcegit/source_git/.packit.yaml
  tests/integration/test_update.py
Labels: mergeit
