Repository packit/packit, pull requests merged in 2020-06, with the labels that each got.

#848 enable overriding package config per job
  packit/config/job_config.py
  packit/config/package_config.py
  packit/schema.py
  tests/unit/test_package_config.py
Labels: mergeit, 🌞 Friday 🤟

#849 Add type annotations to copr code
  packit/copr_helper.py
Labels: mergeit

#851 Add copr build for master
  .packit.yaml
  README.md
Labels: mergeit

#852 Add spaces to copr instructions
  packit/copr_helper.py
Labels: mergeit

#850 Allow dumping of the package config
  packit/schema.py
  tests/unit/test_package_config.py
Labels: mergeit

#853 pc.set_job_overrides: do heavy lifting only when needed
  packit/config/package_config.py
Labels: mergeit

#854 Allow inheriting from MM23Schema for each config schema
  packit/config/config.py
  packit/config/job_config.py
  packit/config/package_config.py
  packit/config/sync_files_config.py
  packit/schema.py
  tests/unit/test_config.py
  tests/unit/test_package_config.py
Labels: mergeit

#856 Revert "enable overriding package config from job.overrides"
  packit/config/job_config.py
  packit/config/package_config.py
  packit/schema.py
  tests/unit/test_package_config.py
Labels: mergeit, ready-for-review

#857 logging improvements
  packit/cli/build.py
  packit/cli/create_update.py
  packit/cli/packit_base.py
  packit/cli/push_updates.py
  packit/cli/status.py
  packit/cli/sync_from_downstream.py
  packit/cli/types.py
  packit/cli/update.py
  packit/schema.py
Labels: mergeit

#858 enable overriding package config per job
  packit/config/common_package_config.py
  packit/config/job_config.py
  packit/config/notifications.py
  packit/config/package_config.py
  packit/schema.py
  tests/unit/test_config.py
  tests/unit/test_package_config.py
Labels: mergeit, ready-for-review

#859 accept JobConfig and PackageConfig equally
  packit/api.py
  packit/base_git.py
  packit/cli/copr_build.py
  packit/config/common_package_config.py
  packit/config/package_config.py
  packit/distgit.py
  packit/status.py
  packit/upstream.py
  tests/integration/test_get_api.py
Labels: mergeit, ready-for-review

#860 Improve the message when marking issues as stale
  .github/stale.yml
Labels: mergeit

#865 Log str(ex) when a RebaseHelperError is encountered
  packit/specfile.py
Labels: mergeit

#836 fix the tests according to new version of requre
  tests_recording/__init__.py
  tests_recording/test_api.py
  tests_recording/test_status.py
  tests_recording/testbase.py
Labels: mergeit

#869 Remove 'jsonschema' as a dependency
  packit.spec
  setup.cfg
Labels: mergeit

#872 [packit] Copr enhancements
  packit/api.py
  packit/cli/copr_build.py
  packit/config/job_config.py
  packit/copr_helper.py
  packit/schema.py
  tests/unit/test_config.py
Labels: mergeit, 🌞 Friday 🤟

#876 Zuul & pre-commit related changes
  .pre-commit-config.yaml
  .zuul.yaml
  files/zuul-pre-commit.yaml
  packit/api.py
  packit/fedpkg.py
  packit/specfile.py
  packit/upstream.py
  setup.cfg
  tests/integration/test_upstream.py
Labels: mergeit

#871 invoke all commands in shell
  packit/api.py
  packit/base_git.py
  packit/command_handler.py
  packit/utils.py
  tests/data/dg-ogr/.packit.yaml
  tests/unit/test_base_git.py
  tests/unit/test_utils.py
Labels: mergeit, 🌞 Friday 🤟

#870 Copr build naming improvement
  packit/upstream.py
  tests/integration/test_upstream.py
Labels: mergeit

#879 Copr-builds for releases and few changes for master builds
  .packit.yaml
  README.md
Labels: mergeit, 🌞 Friday 🤟

#881 [tests] utilize tmp_path instead of tmpdir
  tests/conftest.py
  tests/functional/test_srpm.py
  tests/integration/conftest.py
  tests/integration/test_get_api.py
  tests/integration/test_pagure.py
  tests/integration/test_upstream.py
  tests/integration/test_using_cockpit.py
  tests/integration/test_using_examples.py
  tests/unit/test_config.py
  tests/unit/test_unicodez.py
Labels: mergeit, 🌞 Friday 🤟

#882 Add missing __repr__()s
  packit/api.py
  packit/copr_helper.py
  packit/distgit.py
  packit/fedpkg.py
  packit/local_project.py
  packit/upstream.py
Labels: mergeit, 🌞 Friday 🤟

#826 Add schema validation
  packit/api.py
  packit/cli/packit_base.py
  packit/cli/validate_config.py
  packit/config/package_config.py
  tests/data/validate_config/packit.json
  tests/integration/test_validate_config.py
Labels: mergeit
