Repository packit/packit, pull requests merged in 2020-01, with the labels that each got.

#644 tidy tests
  tests/integration/test_spec.py
Labels: mergeit

#643 Multiple sources
  packit/api.py
  tests/conftest.py
  tests/data/upstream_git_with_multiple_sources/.packit.json
  tests/data/upstream_git_with_multiple_sources/beer.spec
  tests/functional/test_srpm.py
  tests/spellbook.py
Labels: mergeit

#646 Refactoring of the srpm prepare
  packit/api.py
  packit/local_project.py
  packit/upstream.py
Labels: mergeit

#650 Srpm exceptions
  packit/api.py
  packit/exceptions.py
  packit/upstream.py
Labels: mergeit

#648 Catch no copr owner
  packit/api.py
  packit/copr_helper.py
  tests/integration/test_copr_build.py
Labels: mergeit

#640 Feature/logo
  README.md
  design/export/.DS_Store
  design/export/logo-dark.png
  design/export/logo-extended.jpg
  design/export/logo-extended.png
  design/export/logo-extended.svg
  design/export/logo-guideline.pdf
  design/export/logo-no-borders.jpg
  design/export/logo-no-borders.png
  design/export/logo-square-small-borders.jpg
  design/export/logo-square-small-borders.png
  design/export/logo-text.jpg
  design/export/logo-text.png
  design/export/logo-text.svg
  design/export/logo-white.png
  design/export/logo.png
  design/export/logo.svg
  design/logo-packit.sketch
Labels: mergeit

#651 Fix archive path
  packit/upstream.py
  tests/data/edd/.packit.yaml
  tests/data/edd/LICENSE
  tests/data/edd/Makefile
  tests/data/edd/README.rst
  tests/data/edd/docs/man.rst
  tests/data/edd/edd
  tests/data/edd/edd.spec
  tests/integration/test_using_examples.py
  tests/spellbook.py
Labels: mergeit

#652 Fix srpm create path problems
  packit/api.py
  packit/command_handler.py
  packit/upstream.py
  packit/utils.py
  tests/data/snapd/packaging/fedora/snapd.spec
  tests/data/snapd/packaging/fedora/some-file-to-add
  tests/data/vsftpd/.packit.yaml
  tests/data/vsftpd/AUDIT
  tests/data/vsftpd/BENCHMARKS
  tests/data/vsftpd/BUGS
  tests/data/vsftpd/COPYING
  tests/data/vsftpd/Changelog
  tests/data/vsftpd/EXAMPLE/example
  tests/data/vsftpd/FAQ
  tests/data/vsftpd/Fedora/vsftpd-generator
  tests/data/vsftpd/Fedora/vsftpd.ftpusers
  tests/data/vsftpd/Fedora/vsftpd.pam
  tests/data/vsftpd/Fedora/vsftpd.service
  tests/data/vsftpd/Fedora/vsftpd.spec
  tests/data/vsftpd/Fedora/vsftpd.target
  tests/data/vsftpd/Fedora/vsftpd.user_list
  tests/data/vsftpd/Fedora/vsftpd.xinetd
  tests/data/vsftpd/Fedora/vsftpd@.service
  tests/data/vsftpd/Fedora/vsftpd_conf_migrate.sh
  tests/data/vsftpd/INSTALL
  tests/data/vsftpd/LICENSE
  tests/data/vsftpd/README
  tests/data/vsftpd/README.security
  tests/data/vsftpd/REWARD
  tests/data/vsftpd/RedHat/vsftpd.log
  tests/data/vsftpd/SECURITY/security
  tests/data/vsftpd/SIZE
  tests/data/vsftpd/SPEED
  tests/data/vsftpd/TODO
  tests/data/vsftpd/TUNING
  tests/data/vsftpd/vsftpd.8
  tests/data/vsftpd/vsftpd.conf
  tests/data/vsftpd/vsftpd.conf.5
  tests/functional/test_srpm.py
  tests/integration/test_using_examples.py
  tests/spellbook.py
Labels: mergeit

#653 Better SRPM exception messages
  packit/exceptions.py
  packit/upstream.py
  tests/integration/test_upstream.py
Labels: mergeit

#659 don't download remote sources when "sources" path exists in upstream
  packit/upstream.py
  tests/data/osbuild/osbuild.spec
  tests/data/osbuild/sources/test
Labels: mergeit

#661 authentication fixed
  packit/config/config.py
  packit/schema.py
Labels: mergeit

#660 No testingfarm on rawhide because of the marshmallow
  .packit.yaml
Labels: mergeit

#663 Allow list in action commands
  packit/base_git.py
  tests/unit/test_upstream.py
Labels: mergeit

#666 new config opt: exclude paths from patching
  packit/config/package_config.py
  packit/schema.py
  packit/upstream.py
  tests/data/sourcegit/source_git/.packit.yaml
  tests/data/sourcegit/source_git/ignored_file.txt
  tests/integration/test_source_git.py
Labels: ready-for-review, source-git

#664 Use same exception for config missing or invalid
  packit/config/package_config.py
Labels: mergeit

#658 build in koji from srpm
  packit/api.py
  packit/base_git.py
  packit/cli/build.py
  packit/exceptions.py
  packit/fedpkg.py
  packit/upstream.py
  packit/utils.py
  tests/data/upstream_git_with_multiple_sources/beer.spec
  tests/integration/conftest.py
  tests/integration/test_build.py
  tests/integration/test_source_git.py
  tests/integration/test_update.py
  tests/unit/test_utils.py
Labels: mergeit, ready-for-review

#668 add tests for package_config.job.job
  tests/unit/test_config.py
Labels: mergeit

#676 Use lists for default job targets
  packit/config/job_config.py
  tests/unit/test_config.py
Labels: mergeit

#677 upstream,srpm: prepend dash in the changelog entry
  packit/upstream.py
  tests/integration/test_upstream.py
Labels: mergeit

#670 [packit build] Catch an excpetion when failure on fedpkg side
  packit/fedpkg.py
Labels: mergeit

#678 Check downstream branch is clean before sync_release
  packit/api.py
Labels: mergeit

#680 Update spec when getting versions from different branches
  packit/status.py
Labels: mergeit

#682 Use instance url from configuration
  packit/config/config.py
Labels: mergeit

#685 [get_package_config_from_repo] Don't print a message for every not-found file.
  packit/config/package_config.py
Labels: mergeit

#687 Add a new command for local build
  packit/api.py
  packit/cli/local_build.py
  packit/cli/packit_base.py
  packit/exceptions.py
  packit/upstream.py
  tests/functional/test_local_build.py
Labels: mergeit
