Repository packit/packit, pull requests merged in 2020-08, with the labels that each got.

#920 zuul: org rename
  .zuul.yaml
  files/zuul-reverse-dep-packit-service.yaml
Labels: mergeit

#923 [srpm] Extend logging of paths and make path to archive explicit
  packit/upstream.py
Labels: mergeit, ready-for-review

#921 copr settings updates
  packit/api.py
  packit/cli/copr_build.py
  packit/copr_helper.py
  packit/exceptions.py
  tests/integration/test_copr_build.py
Labels: ready-for-review

#927 Edit copr settings only for accessible attributes
  packit/copr_helper.py
  tests/integration/test_copr_build.py
Labels: mergeit

#929 Call the method on right copr object
  packit/copr_helper.py
  tests/integration/test_copr_build.py
Labels: mergeit

#928 Use 'create_pr' instead of 'pr_create'
  packit/distgit.py
  packit/upstream.py
  tests/integration/conftest.py
  tests/integration/test_pagure.py
  tests/unit/test_upstream.py
Labels: mergeit

#832 Split utils into modules
  packit/api.py
  packit/base_git.py
  packit/cli/packit_base.py
  packit/cli/types.py
  packit/command_handler.py
  packit/config/aliases.py
  packit/distgit.py
  packit/fedpkg.py
  packit/local_project.py
  packit/patches.py
  packit/upstream.py
  packit/utils.py
  packit/utils/__init__.py
  packit/utils/commands.py
  packit/utils/extensions.py
  packit/utils/logging.py
  packit/utils/repo.py
  tests/conftest.py
  tests/functional/test_srpm.py
  tests/functional/test_validate_config.py
  tests/integration/__init__.py
  tests/integration/conftest.py
  tests/integration/test_build.py
  tests/integration/test_generate.py
  tests/integration/test_source_git.py
  tests/integration/test_sync_files.py
  tests/integration/test_upstream.py
  tests/integration/test_using_cockpit.py
  tests/integration/test_using_examples.py
  tests/integration/test_validate_config.py
  tests/integration/utils.py
  tests/spellbook.py
  tests/unit/test_base_git.py
  tests/unit/test_local_project.py
  tests/unit/test_unicodez.py
  tests/unit/test_utils.py
Labels: mergeit

#933 merge related commits into a single patch (git-am)
  packit/base_git.py
  packit/patches.py
  packit/specfile.py
  packit/upstream.py
  tests/data/sourcegit/source_git/fedora/beer.spec
  tests/integration/conftest.py
  tests/integration/test_source_git.py
  tests/spellbook.py
Labels: mergeit, ready-for-review

#938 Allow ignoring updates for Copr boolean values
  packit/api.py
  packit/copr_helper.py
  tests/integration/test_copr_build.py
Labels: mergeit

#940 https://github.com/packit-service -> https://github.com/packit
  .packit.yaml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  README.md
  ci.fmf
  files/tasks/ogr-master.yaml
  files/tasks/requre-master.yaml
  files/tasks/sandcastle-master.yaml
  packit.spec
  packit/actions.py
  packit/api.py
  packit/cli/utils.py
  packit/config/config.py
  packit/copr_helper.py
  packit/distgit.py
  packit/specfile.py
  packit/upstream.py
  packit/utils/commands.py
  setup.cfg
  tests/integration/test_base_git.py
  tests/integration/test_copr_build.py
  tests/integration/test_get_api.py
  tests/unit/test_package_config.py
  tests/unit/test_utils.py
  tests_recording/README.md
  tests_recording/testbase.py
Labels: mergeit

#926 Support gitlab on checkout_pr
  packit/local_project.py
  tests/integration/test_local_project.py
  tests/unit/test_local_project.py
Labels: mergeit

#939 source-git: drop ensure_pnum
  packit/base_git.py
  packit/specfile.py
  tests/data/sourcegit/source_git/fedora/beer.spec
  tests/integration/test_source_git.py
  tests/integration/test_spec.py
Labels: mergeit, ready-for-review

#937 Make LocalProject.working_dir Path instead of str
  packit/api.py
  packit/base_git.py
  packit/cli/init.py
  packit/cli/utils.py
  packit/cli/validate_config.py
  packit/distgit.py
  packit/fedpkg.py
  packit/local_project.py
  packit/upstream.py
  packit/utils/repo.py
  tests/integration/conftest.py
  tests/integration/test_base_git.py
  tests/integration/test_get_api.py
  tests/integration/test_local_project.py
  tests/integration/test_update.py
  tests/integration/test_upstream.py
  tests/integration/test_using_cockpit.py
  tests/integration/test_using_examples.py
  tests/unit/test_local_project.py
  tests/unit/test_upstream.py
  tests_recording/test_api.py
  tests_recording/testbase.py
Labels: mergeit

#944 m0ar logging for some copr operations
  packit/api.py
  packit/copr_helper.py
Labels: mergeit

#945 [config/aliases.py] Fedora 33 has been branched from rawhide
  packit.spec
  packit/config/aliases.py
  tests/unit/test_config_aliases.py
Labels: mergeit

#949 Append copr chroots
  packit/copr_helper.py
  tests/integration/test_copr_build.py
Labels: mergeit

#950 improve action output logging
  packit/base_git.py
  packit/command_handler.py
  tests/functional/spellbook.py
  tests/functional/test_srpm.py
  tests/unit/test_base_git.py
Labels: mergeit, ready-for-review

#951 fixup sandcastle logging: exec returns str, not List[str]
  packit/command_handler.py
  tests/unit/test_base_git.py
Labels: mergeit
