Repository packit/packit, pull requests merged in 2021-03, with the labels that each got.

#1131 Support sources in configuration
  packit/base_git.py
  packit/config/common_package_config.py
  packit/config/job_config.py
  packit/config/package_config.py
  packit/config/sources.py
  packit/distgit.py
  packit/schema.py
  packit/upstream.py
  tests/integration/conftest.py
  tests/unit/test_base_git.py
  tests/unit/test_package_config.py
Labels: mergeit

#1129 command_handler: run all actions in a single sandbox
  packit/api.py
  packit/base_git.py
  packit/command_handler.py
  tests/unit/test_base_git.py
Labels: mergeit

#1136 0.26.0 release
  CHANGELOG.md
  packit.spec
Labels: mergeit

#1138 make sandcastle-related tests pass
  files/packit-testing-farm-prepare.yaml
  tests/unit/test_base_git.py
Labels: mergeit

#1137 patches: dont run linearization if the repo is dirty
  packit/exceptions.py
  packit/patches.py
  tests/integration/test_source_git.py
Labels: mergeit

#1141 patches: run linearization commands in the repo
  packit/base_git.py
  packit/local_project.py
  packit/patches.py
  tests/integration/test_source_git.py
Labels: mergeit

#1143 pc.sources: fetch all by default
  packit/base_git.py
  tests/unit/test_base_git.py
  tests_recording/test_base_git.py
  tests_recording/test_data/test_base_git/tests_recording.test_base_git.ProposeUpdate.test_download_remote_sources_via_spec.yaml
Labels: mergeit

#1145 packit.yaml: create downstream %changelog from git-log
  .packit.yaml
Labels: mergeit

#1133 propose-downstream: Detect identical patches
  .pre-commit-config.yaml
  packit/api.py
  packit/patches.py
  packit/utils/repo.py
  tests/data/patches/previous/git-diff.patch
  tests/data/patches/previous/missing-diff-line.patch
  tests/data/patches/previous/unified-diff.patch
  tests/data/patches/previous/weird-identical.patch
  tests/data/patches/regenerated/git-diff.patch
  tests/data/patches/regenerated/missing-diff-line.patch
  tests/data/patches/regenerated/unified-diff.patch
  tests/data/patches/regenerated/weird-identical.patch
  tests/integration/test_patches.py
  tests/integration/test_source_git.py
  tests/unit/test_api.py
  tests/unit/test_utils.py
Labels: mergeit

#1144 linearization: properly check out the temp branch
  packit/patches.py
  tests/integration/test_source_git.py
Labels: mergeit

#1150 Workflow for uploading release to PyPI
  .github/workflows/pypi-publish.yml
Labels: mergeit

#1158 prepare upstream for srpm: better error message
  packit/api.py
Labels: mergeit

#1159 build/CI related refactoring
  .zuul.yaml
  Dockerfile
  Dockerfile.tests
  Makefile
  Vagrantfile
  files/install-requirements-git.yaml
  files/install-requirements-pip.yaml
  files/install-requirements-rpms.yaml
  files/local-tests-requirements.yaml
  files/tasks/generic-dnf-requirements.yaml
  files/zuul-install-requirements-rpms.yaml
Labels: mergeit

#1162 packit.yaml: build latest for all Fedora and EPEL
  .packit.yaml
Labels: mergeit

#1163 [sync_from_downstream] add option to sync only specfile
  packit/api.py
  packit/config/common_package_config.py
Labels: mergeit

#1164 Specfile:add_patch(): find first empty line after last_source_tag_line
  packit/specfile.py
  tests/integration/test_source_git.py
Labels: mergeit

#1166 0.27.0 release
  .packit.yaml
  CHANGELOG.md
  packit.spec
Labels: mergeit

#1155 Add test repo reference to package-config
  packit/config/job_config.py
  packit/schema.py
  tests/unit/test_package_config.py
Labels: mergeit

#1165 source-git: Store downstream packaging files in '.distro'
  packit/distgit.py
  tests/data/sourcegit/source_git/.distro/beer.spec
  tests/data/sourcegit/source_git/.packit.yaml
  tests/integration/test_source_git.py
Labels: mergeit

#1178 Remove 'load_config' and 'dump_config'
  packit/schema.py
Labels: mergeit

#1167 Treat centos-stream as centos-stream-8
  packit/cli/copr_build.py
  packit/config/aliases.py
  packit/schema.py
  tests/unit/test_config_aliases.py
Labels: mergeit

#1179 Actions/workflow: don't build & push packit-tests image
  .github/workflows/build-and-push.yml
Labels: mergeit

#1177 init: enable using Stream 9 dist-git as a source
  packit/cli/init.py
  packit/cli/utils.py
  packit/constants.py
  packit/exceptions.py
  packit/source_git.py
  packit/utils/repo.py
  tests/integration/test_source_git_generator.py
  tests/unit/test_source_git_generator.py
Labels: mergeit, ready-for-review

#1171 Remove dry-run
  packit/cli/packit_base.py
  packit/config/config.py
  packit/schema.py
  tests_recording/testbase.py
Labels: mergeit

#1183 download_remote_sources: dont download a source twice
  packit/base_git.py
  tests/unit/test_base_git.py
Labels: mergeit, 🌞 Friday 🤟

#1182 Rebase patches against HEAD branch, not `master`
  packit/source_git.py
  packit/utils/repo.py
Labels: mergeit

#1175 Allow only signed commits to be proposed downstream
  .packit.yaml
Labels: mergeit

#1188 Explicitly require setuptools, packit/__init__.py imports from pkg_resources
  setup.cfg
Labels: mergeit

#1184 Add -c option to specify custom package config
  packit/cli/packit_base.py
  packit/cli/utils.py
  packit/config/config.py
  packit/config/package_config.py
  packit/schema.py
  tests/unit/test_package_config.py
Labels: mergeit

#1187 Introduce fedora-latest alias
  packit/config/aliases.py
  tests/unit/test_config_aliases.py
Labels: mergeit
