Repository packit/packit, pull requests merged in 2021-11, with the labels that each got.

#1403 Reflect ogr changes in integration tests
  tests/integration/conftest.py
  tests/integration/test_pagure.py
Labels: mergeit

#1405 Update backup ALIASES
  packit/config/aliases.py
Labels: mergeit

#1406 Handle patch content which has unknown encoding
  packit/patches.py
  tests/data/patches/previous/unified-diff.patch
Labels: mergeit, has-release-notes

#1408 Fix flexmock imports
  tests/integration/test_patches.py
  tests/integration/test_source_git_init.py
  tests/integration/test_spec.py
  tests/unit/test_patches.py
Labels: mergeit

#1367 Changelog refactor
  packit/actions.py
  packit/api.py
  packit/cli/__init__.py
  packit/cli/build.py
  packit/cli/copr_build.py
  packit/cli/create_update.py
  packit/cli/init.py
  packit/cli/propose_downstream.py
  packit/cli/push_updates.py
  packit/cli/srpm.py
  packit/cli/status.py
  packit/cli/sync_from_downstream.py
  packit/cli/utils.py
  packit/command_handler.py
  packit/config/config.py
  packit/exceptions.py
  packit/local_project.py
  packit/security.py
  packit/upstream.py
  packit/utils/changelog_helper.py
  tests/__init__.py
  tests/functional/__init__.py
  tests/functional/spellbook.py
  tests/functional/test_srpm.py
  tests/functional/test_validate_config.py
  tests/integration/__init__.py
  tests/integration/bodhi_latest_builds.py
  tests/integration/bodhi_status_updates.py
  tests/integration/test_actions.py
  tests/integration/test_api.py
  tests/integration/test_base_git.py
  tests/integration/test_build.py
  tests/integration/test_changelog_helper.py
  tests/integration/test_create_update.py
  tests/integration/test_distgit.py
  tests/integration/test_get_api.py
  tests/integration/test_pagure.py
  tests/integration/test_push_updates.py
  tests/integration/test_update.py
  tests/integration/test_upstream.py
  tests/integration/test_using_cockpit.py
  tests/integration/test_using_examples.py
  tests/integration/utils.py
  tests/spellbook.py
  tests/unit/__init__.py
  tests/unit/test_actions.py
  tests/unit/test_base_git.py
  tests/unit/test_cli.py
  tests/unit/test_cli_utils.py
  tests/unit/test_config_aliases.py
  tests/unit/test_local_project.py
  tests/unit/test_security.py
  tests/unit/test_unicodez.py
  tests/unit/test_upstream.py
  tests_recording/test_api.py
  tests_recording/test_status.py
  tests_recording/testbase.py
Labels: high-prio, mergeit, has-release-notes

#1416 Prepare release 0.41.0
  CHANGELOG.md
  packit.spec
Labels: mergeit

#1421 Run post_upstream_clone immediately when updating
  packit/api.py
  tests/integration/test_update.py
Labels: mergeit

#1411 Add environment config option
  packit/config/job_config.py
  packit/schema.py
  tests/unit/test_package_config.py
Labels: mergeit

#1423 Add missing 'f' to a string
  packit/config/aliases.py
Labels: mergeit

#1415 Add downstream Koji build as new type
  packit/config/job_config.py
Labels: mergeit

#1426 Release 0.42.0
  CHANGELOG.md
  packit.spec
Labels: mergeit

#1427 Introduce PackitMissingConfigException class
  packit/exceptions.py
Labels: mergeit
