Repository packit/packit, pull requests merged in 2022-03, with the labels that each got.

#1498 Multiple fixes to improve using source script
  packit/config/package_config.py
  packit/utils/source_script.py
  tests/unit/test_utils.py
Labels: mergeit

#1504 feat(copr): allow disabling of network for Copr builds
  packit/api.py
  packit/cli/copr_build.py
  packit/config/job_config.py
  packit/schema.py
  tests/integration/test_copr_build.py
Labels: mergeit, copr, 🌞 friday 🤟

#1506 Add a new job config option for identifying the job
  packit/config/common_package_config.py
  packit/config/job_config.py
Labels: mergeit

#1507 Add job identifier to the config schema
  packit/config/job_config.py
  packit/config/package_config.py
  packit/schema.py
Labels: mergeit

#1514 Simplify LocalProject
  packit/api.py
  packit/local_project.py
  packit/utils/repo.py
  tests/unit/test_local_project.py
  tests/unit/test_utils.py
Labels: refactor, mergeit, 🌞 friday 🤟

#1513 feat(aliases,copr): switch to TTL cache
  .pre-commit-config.yaml
  files/install-requirements-pip.yaml
  packit.spec
  packit/config/aliases.py
  packit/copr_helper.py
  setup.cfg
Labels: user-experience, fedora, refactor, mergeit, copr, 🌞 friday 🤟, has-release-notes

#1512 feat(aliases): expand git aliases for events
  packit/config/aliases.py
Labels: mergeit

#1517 FAS authentication for Bodhi
  packit/api.py
  packit/config/aliases.py
  packit/config/config.py
  packit/distgit.py
  packit/schema.py
  packit/status.py
  packit/utils/bodhi.py
  tests/integration/test_create_update.py
  tests/unit/test_config_aliases.py
Labels: mergeit

#1518 Prepare release 0.47.1
  CHANGELOG.md
  packit.spec
Labels: mergeit

#1524 With the new `files_to_sync` key, the spec-file and Packit config needs to be set
  .packit.yaml
Labels: mergeit

#1528 Make the work with Bodhi more robust
  packit/distgit.py
  packit/utils/bodhi.py
Labels: mergeit

#1531 Support for packit instances
  packit/config/common_package_config.py
  packit/config/job_config.py
  packit/config/package_config.py
  packit/schema.py
Labels: mergeit

#1533 fix(tests): Try the latest python3-flexmock
  files/tasks/rpm-test-deps.yaml
Labels: mergeit

#1527 fix(copr): do not error out for already created repo
  packit/copr_helper.py
  tests/integration/test_copr_build.py
Labels: mergeit

#1532 Fix the files_to_sync field in the serialized object
  packit/config/__init__.py
  packit/config/common_package_config.py
  packit/schema.py
  tests/unit/test_package_config.py
Labels: mergeit

#1538 Use both production and staging instance of Packit
  .packit.yaml
Labels: mergeit

#1539 Release 0.48.0
  CHANGELOG.md
  packit.spec
Labels: mergeit
