Repository packit/packit, pull requests merged in 2022-02, with the labels that each got.

#1470 Introduce option for not requiring %autosetup for source-git init command
  packit/api.py
  packit/cli/source_git_init.py
  packit/source_git.py
  tests/integration/test_source_git_init.py
Labels: mergeit

#1471 Create bodhi update via Packit for completed Koji builds
  .packit.yaml
Labels: mergeit

#1474 Release 0.45.0
  CHANGELOG.md
  packit.spec
Labels: mergeit

#1478 Handle colon in git trailer values
  packit/patches.py
  tests/unit/test_patches.py
Labels: mergeit

#1480 Update aliases, Fedora Linux 36 was branched
  packit/config/aliases.py
Labels: mergeit

#1479 PR template: clearly mark release notes
  .github/PULL_REQUEST_TEMPLATE.md
Labels: mergeit

#1485 0.46.0 release
  CHANGELOG.md
  packit.spec
Labels: mergeit

#1484 Use the new 'files_to_sync' config key in source-git init
  packit/source_git.py
  tests/integration/test_source_git_init.py
Labels: mergeit

#1489 Add 'srpm_build_deps' configuration key for package config
  packit/config/common_package_config.py
  packit/config/job_config.py
  packit/config/package_config.py
  packit/schema.py
  tests/unit/test_package_config.py
Labels: mergeit

#1488 Update `source-git` commands to mark commit origin
  packit/api.py
  packit/base_git.py
  packit/cli/source_git_init.py
  packit/cli/update_dist_git.py
  packit/cli/update_source_git.py
  packit/constants.py
  packit/source_git.py
  tests/integration/test_source_git.py
  tests/integration/test_source_git_init.py
  tests/integration/test_source_git_update_source_git.py
Labels: mergeit, has-release-notes

#1490 packit.yaml: build our SRPM in Copr
  .packit.yaml
  packit/constants.py
  tests/unit/test_utils.py
Labels: ready-for-review, mergeit

#1496 new tmt plan: rpmlint packit.spec
  plans/rpmlint.fmf
Labels: mergeit
