Repository packit/packit, pull requests merged in 2022-01, with the labels that each got.

#1445 lp,no-merge-pr: check out to pr/{pr_id}
  packit/local_project.py
  tests_recording/test_data/test_local_project/ProposeUpdate.test_checkout_pr.yaml
  tests_recording/test_data/test_local_project/ProposeUpdate.test_checkout_pr_no_merge.yaml
  tests_recording/test_local_project.py
Labels: mergeit, 🌞 friday 🤟

#1446 merging PRs: PR into target, rename after
  packit/constants.py
  packit/local_project.py
  tests/integration/test_local_project.py
  tests_recording/test_local_project.py
Labels: mergeit

#1448 Add flexmock to testing dependencies
  .pre-commit-config.yaml
  setup.cfg
Labels: mergeit

#1452 Do not ignore --no-bump and --release-suffix for src-git repos
  packit/upstream.py
  packit/utils/changelog_helper.py
Labels: mergeit, 🌞 friday 🤟

#1449 do NOT delete /tmp when tearing down recording tests
  tests_recording/test_data/test_local_project/ProposeUpdate.test_checkout_pr.yaml
  tests_recording/test_data/test_local_project/ProposeUpdate.test_checkout_pr_no_merge.yaml
  tests_recording/test_data/test_local_project/TestLocalProject.test_checkout_pr.yaml
  tests_recording/test_data/test_local_project/TestLocalProject.test_checkout_pr_no_merge.yaml
  tests_recording/test_local_project.py
  tests_recording/test_repository_cache.py
  tests_recording/testbase.py
Labels: mergeit, 🌞 friday 🤟

#1455 tests: check that merged PR matches main's HEAD
  tests_recording/test_local_project.py
Labels: mergeit

#1458 Allow git trees with .git gitdir reference files
  packit/utils/repo.py
Labels: mergeit

#1459 Release 0.44.0
  CHANGELOG.md
  packit.spec
Labels: mergeit

#1453 Preserve %autochangelog in downstream spec file
  packit/base_git.py
  packit/specfile.py
  packit/utils/changelog_helper.py
  tests/conftest.py
  tests/data/dist_git_with_autochangelog/.packit.json
  tests/data/dist_git_with_autochangelog/beer.spec
  tests/integration/conftest.py
  tests/integration/test_changelog_helper.py
  tests/integration/test_update.py
  tests/spellbook.py
  tests/unit/test_specfile.py
Labels: mergeit

#1461 Skip %autochangelog tests if rpm < 4.16
  tests/integration/test_changelog_helper.py
  tests/unit/test_specfile.py
Labels: mergeit

#1456 Implement update-source-git command
  packit/api.py
  packit/cli/source_git.py
  packit/cli/update_source_git.py
  packit/local_project.py
  tests/integration/test_source_git_update_source_git.py
  tests/unit/test_local_project.py
Labels: mergeit

#1460 Apply code suggestions by Sourcery
  packit/actions.py
  packit/api.py
  packit/base_git.py
  packit/cli/types.py
  packit/config/package_config.py
  packit/local_project.py
  packit/schema.py
  packit/source_git.py
  packit/specfile.py
  packit/sync.py
  packit/upstream.py
  packit/utils/repo.py
  tests/conftest.py
  tests/integration/test_patches.py
  tests/integration/test_source_git.py
  tests/unit/conftest.py
  tests_recording/test_status.py
Labels: refactor, mergeit, 🌞 friday 🤟

#1463 Update classifiers to mark support for Python 3.9 and 3.10
  setup.cfg
Labels: mergeit

#1464 Update the examples in the 'update-dist-git' help text
  packit/cli/update_dist_git.py
Labels: mergeit

#1462 Use target_branch argument for prepare-sources command for merging PR
  packit/cli/prepare_sources.py
  packit/cli/types.py
  packit/local_project.py
  packit/utils/source_script.py
  tests/unit/test_utils.py
Labels: mergeit

#1466 Add a new job type for automatically created Bodhi updates
  packit/config/job_config.py
Labels: mergeit

#1467 Configure git user and mail in the source script
  packit/constants.py
  tests/unit/test_utils.py
Labels: mergeit

#1465 Disable creating of the sync note file (aka README.packit)
  packit/api.py
  packit/config/common_package_config.py
  packit/config/job_config.py
  packit/config/package_config.py
  packit/schema.py
  tests/unit/conftest.py
  tests/unit/test_api.py
  tests/unit/test_package_config.py
Labels: mergeit
