Repository packit/packit, pull requests merged in 2022-11, with the labels that each got.

#1727 Support monorepo config
  files/tasks/rpm-test-deps.yaml
  packit/api.py
  packit/base_git.py
  packit/cli/utils.py
  packit/config/__init__.py
  packit/config/common_package_config.py
  packit/config/job_config.py
  packit/config/package_config.py
  packit/config/package_config_validator.py
  packit/distgit.py
  packit/schema.py
  packit/status.py
  packit/upstream.py
  packit/utils/changelog_helper.py
  tests/conftest.py
  tests/integration/test_base_git.py
  tests/integration/test_get_api.py
  tests/integration/test_validate_config.py
  tests/unit/test_base_git.py
  tests/unit/test_config.py
  tests/unit/test_dg.py
  tests/unit/test_package_config.py
  tests/unit/test_prepare_sources.py
  tests/unit/test_propose_downstream.py
  tests_recording/test_base_git.py
Labels: ready-for-review

#1758 Fix setting the default value of 'specfile_path'
  packit/config/package_config.py
  tests/unit/test_package_config.py
Labels: ready-for-review, mergeit

#1763 Remove workaround for old pytest version in EL 8
  plans/full.fmf
  setup.cfg
  tests/conftest.py
  tests/full.fmf
Labels: mergeit

#1766 Fix typo in create_bodhi_update()
  packit/distgit.py
Labels: mergeit

#1769 Correctly process empty configs loaded remotely
  packit/config/package_config.py
  tests/unit/test_package_config.py
Labels: mergeit

#1764 Add methods to get build dicts from KojiHelper
  packit/distgit.py
  packit/status.py
  packit/utils/koji_helper.py
  tests/unit/test_utils.py
Labels: mergeit

#1775 Fix release for a fix_spec action with macros
  packit/upstream.py
  tests/integration/test_upstream.py
  tests/unit/test_upstream.py
Labels: mergeit

#1793 Remove Python 3.6 compatibility code from 'packit status'
  README.md
  packit/api.py
Labels: mergeit

#1778 Multi-source RPM support in propose-downstream
  packit/api.py
  packit/base_git.py
  packit/config/common_package_config.py
  packit/distgit.py
  packit/pkgtool.py
  packit/upstream.py
  packit/utils/changelog_helper.py
  tests/data/upstream_git/beer.spec
  tests/integration/conftest.py
  tests/integration/test_update.py
  tests/integration/test_upstream.py
  tests/integration/test_using_cockpit.py
Labels: mergeit
