Repository packit/packit, pull requests merged in 2023-02, with the labels that each got.

#1843 Bump prepare-release version
  .github/workflows/prepare-release.yml
Labels: mergeit

#1810 feat(cli,build): implement local build from SRPM
  packit/cli/builds/local_build.py
  packit/upstream.py
  tests/functional/test_local_build.py
Labels: mergeit, 🌞 friday 🤟

#1844 chore(bodhi): utilize upstream bodhi functionality
  packit.spec
  packit/api.py
  packit/distgit.py
  packit/utils/bodhi.py
  setup.cfg
  tests/integration/test_create_update.py
  tests/integration/test_push_updates.py
  tests/unit/test_login_with_kerberos.py
  tests/unit/test_status.py
Labels: ready-for-review, mergeit

#1853 Provide version env var in changelog-entry action
  packit/utils/changelog_helper.py
  tests/integration/test_changelog_helper.py
Labels: mergeit

#1857 Always set version, disregarding update_release value
  packit/api.py
  packit/cli/prepare_sources.py
  packit/cli/srpm.py
  packit/config/common_package_config.py
  packit/upstream.py
  packit/utils/changelog_helper.py
  tests/unit/test_upstream.py
Labels: mergeit

#1858 Do not try to parse empty version
  packit/upstream.py
Labels: mergeit

#1862 Update the alias mapping for Fedora Linux
  packit/config/aliases.py
Labels: mergeit

#1861 better wording when packit cannot parse YAML file
  packit/config/package_config.py
Labels: mergeit

#1863 fix(aliases,bodhi): account for state frozen
  packit/config/aliases.py
  tests/unit/test_config_aliases.py
Labels: mergeit
